# Generated by Django 5.1.3 on 2024-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionmodel',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
